# GET http://localhost:8000/users/token/dondon
GET https://sml-backend.herokuapp.com/users/token/6350fde7-f443-48d7-bcfb-0c2257e32caa

###

GET http://localhost:8000/users/5
Authorization: 6350fde7-f443-48d7-bcfb-0c2257e32caa

###

POST http://localhost:8000/users/signup
# POST https://sml-backend.herokuapp.com/users/signup
Content-Type: application/json

{
    "userName": "taha",
    "email": "abdurashidovtadsfhaY@yandex.com",
    "password": "hey"
}

###

# POST http://localhost:8000/users/signup/code
POST https://sml-backend.herokuapp.com/users/signup/code
Content-Type: application/json

{
    "code": "0d26fe35-2364-4243-b000-5b19aac5cc3d"
}

###

POST http://localhost:8000/sml/users/login
# POST https://sml-backend.herokuapp.com/users/login
Content-Type: application/json

{
    "email": "abdurashidovtaha2@gmail.com",
    "password": "hey"
}

###
# GET http://localhost:8000/products/categories
GET https://sml-backend.herokuapp.com/products/categories
Authorization: 7f7fd056-32f1-4cf5-a123-f8496b4fb524

###

DELETE https://sml-backend.herokuapp.com/sml/products/all
# Authorization: admin1982

###
# POST http://localhost:8000/products
POST https://sml-backend.herokuapp.com/products
Content-Type: application/json
Authorization: 7f7fd056-32f1-4cf5-a123-f8496b4fb524

{
    "categoryID": 95,
    "title": "jaga",
    "price": "300000",
    "bargain": true,
    "description": "Hama tenjay, tovar devonaashay",
    "phoneNumber": 91292192,
    "pictures": [
    ],
    "fields": [
        {
            "id": 5,
            "value": 1200
        },
        {
            "id": 15,
            "value": "20207 $"
        },
        {
            "id": 25,
            "value": "632 km/h"
        }
    ]
}

###
# GET http://localhost:8000/products
GET https://sml-backend.herokuapp.com/sml/products
Authorization: 6350fde7-f443-48d7-bcfb-0c2257e32caa


###
GET http://localhost:8000/products/accepted
Authorization: 6350fde7-f443-48d7-bcfb-0c2257e32caa


###
GET http://localhost:8000/products/declined
Authorization: dondon

###
# GET http://localhost:8000/products/que
GET https://sml-backend.herokuapp.com/products/que
Authorization: 6350fde7-f443-48d7-bcfb-0c2257e32caa

###
GET http://localhost:8000/products/admin
# GET https://sml-backend.herokuapp.com/products/admin
Authorization: 6350fde7-f443-48d7-bcfb-0c2257e32caa

###
# PATCH http://localhost:8000/products/admin/product
PATCH https://sml-backend.herokuapp.com/products/admin/product
Authorization: 6350fde7-f443-48d7-bcfb-0c2257e32caa
Content-Type: application/json

{
    "id": 375,
    "value": 2
}

###
# GET http://localhost:8000/products/single/375
GET https://sml-backend.herokuapp.com/products/single/375
Authorization: 7f7fd056-32f1-4cf5-a123-f8496b4fb524
